// Auto-generated by scripts/build_search_index.py. Do not edit by hand,
// edit index.html's project cards and rerun the script instead.
const SEARCH_INDEX = [
  {
    "title": "State of Decay 3",
    "role": "Games Programmer \u00b7 Wushu Studios (2023\u20132026) Contracted by Undead Labs, Microsoft",
    "url": "projects/sod3.html",
    "tags": [
      "C++",
      "Unreal Engine 5",
      "Perforce",
      "Gameplay Systems"
    ]
  },
  {
    "title": "Fall Guys",
    "role": "Games Programmer \u00b7 Wushu Studios (2023) Contracted by Mediatonic, Epic Games",
    "url": "projects/fallguys.html",
    "tags": [
      "C#",
      "Unity",
      "Perforce",
      "Editor Tooling"
    ]
  },
  {
    "title": "Destruction AllStars",
    "role": "Junior Programmer \u00b7 Wushu Studios (2019\u20132021) Contracted by Lucid Games, Sony",
    "url": "projects/das.html",
    "tags": [
      "C++",
      "Unreal Engine",
      "Perforce",
      "Multiplayer"
    ]
  },
  {
    "title": "Aljakun",
    "role": "Solo project \u00b7 Ongoing \u00b7 programmer, systems designer & AI",
    "url": "projects/aljakun.html",
    "tags": [
      "C#",
      "Unity",
      "Git",
      "UI Toolkit",
      "Unity Sentis",
      "DOTween",
      "NUnit",
      "Procedural Generation",
      "Custom Editor Tooling"
    ]
  },
  {
    "title": "RedMirror",
    "role": "Solo project \u00b7 2021 \u00b7 programmer, network architect & designer",
    "url": "projects/redmirror.html",
    "tags": [
      "C#",
      "Unity 2020.3",
      "Git",
      "Mirror Networking",
      "NavMesh",
      "Odin",
      "DOTween",
      "ParrelSync",
      "Dedicated Server",
      "Fog of War"
    ]
  },
  {
    "title": "Niloc",
    "role": "Programmer / Project Manager \u00b7 Major Project (2019) \u00b7 team of 6 (+3 outsourced)",
    "url": "projects/niloc.html",
    "tags": [
      "C#",
      "Unity 2018.3 (HDRP)",
      "Git",
      "FMOD",
      "Odin",
      "DOTween",
      "Rewired",
      "Cinemachine",
      "Object Pooling",
      "Custom Editor Tooling"
    ]
  },
  {
    "title": "Robrawl",
    "role": "Programmer / Project Manager \u00b7 Brains Eden (2019) \u00b7 team of 5",
    "url": "projects/robrawl.html",
    "tags": [
      "C#",
      "Unity 2019.1 (LWRP)",
      "Git",
      "Rewired",
      "Odin",
      "DOTween",
      "TextMesh Pro",
      "Local Multiplayer"
    ]
  },
  {
    "title": "WorldCraft",
    "role": "Solo project \u00b7 Advanced Games Implementation Project (2019)",
    "url": "projects/worldcraft.html",
    "tags": [
      "C++",
      "Unreal Engine 4",
      "Git",
      "Procedural Generation",
      "Voxel Terrain",
      "Simplex Noise"
    ]
  },
  {
    "title": "Plucky",
    "role": "Solo project \u00b7 2nd-Year University Project (2018)",
    "url": "projects/plucky.html",
    "tags": [
      "C#",
      "Unity",
      "Git",
      "VRTK",
      "Odin",
      "DOTween",
      "Finite State Machine AI",
      "Blender"
    ]
  },
  {
    "title": "Venture",
    "role": "Solo project \u00b7 University Module Project (2018)",
    "url": "projects/venture.html",
    "tags": [
      "C#",
      "Unity3D",
      "Git",
      "Procedural Generation",
      "Object Pooling",
      "Accelerometer Controls",
      "Photoshop",
      "BFXR"
    ]
  },
  {
    "title": "Badwiches",
    "role": "Programmer / Project Manager \u00b7 Ludum Dare 45 (2019) \u00b7 team of 5",
    "url": "projects/badwiches.html",
    "tags": [
      "C++",
      "Unreal Engine",
      "Git",
      "Maya",
      "ZBrush",
      "Substance Painter",
      "Photoshop",
      "FMOD Studio",
      "LMMS"
    ]
  },
  {
    "title": "Ferral",
    "role": "Solo project \u00b7 University Game Jam (2018)",
    "url": "projects/ferral.html",
    "tags": [
      "C#",
      "Unity3D",
      "Git",
      "Local Multiplayer",
      "Blender",
      "Photoshop",
      "Mixamo"
    ]
  },
  {
    "title": "DataSkream",
    "role": "Programmer \u00b7 Ludum Dare 42 (2018) \u00b7 team of 4",
    "url": "projects/dataskream.html",
    "tags": [
      "C#",
      "Unity",
      "Git",
      "Odin",
      "DOTween",
      "Amplify Shader Editor",
      "Blender",
      "Maya",
      "ZBrush",
      "Photoshop",
      "Ableton Live"
    ]
  },
  {
    "title": "Lumina",
    "role": "Programmer / 3D Artist / PM \u00b7 Alakajam #3 (2018) \u00b7 team of 4",
    "url": "projects/lumina.html",
    "tags": [
      "C#",
      "Unity",
      "Git",
      "Maya",
      "Blender",
      "Substance Painter",
      "Photoshop",
      "Bosca Ceoil"
    ]
  },
  {
    "title": "Gallant",
    "role": "Solo project \u00b7 University Game Jam (2018)",
    "url": "projects/gallant.html",
    "tags": [
      "C#",
      "Unity3D",
      "Git",
      "Local Multiplayer",
      "Blender"
    ]
  },
  {
    "title": "The Exalted",
    "role": "Solo project \u00b7 Ludum Dare 40 (2017)",
    "url": "projects/the-exalted.html",
    "tags": [
      "C#",
      "Unity3D",
      "Git",
      "Photoshop",
      "BFXR",
      "Bosca Ceoil"
    ]
  },
  {
    "title": "Valiant",
    "role": "Solo project \u00b7 Charity Game Jam (2017)",
    "url": "projects/valiant.html",
    "tags": [
      "C#",
      "Unity3D",
      "Git",
      "Accelerometer Controls",
      "Photoshop",
      "Bosca Ceoil"
    ]
  },
  {
    "title": "Sqube",
    "role": "Artist / Designer \u00b7 Dare to be Digital (2016) \u00b7 team of 8",
    "url": "projects/sqube.html",
    "tags": [
      "Level Design",
      "Physical Prototyping",
      "Blender",
      "Photoshop"
    ]
  }
];
