#!/usr/bin/env python3
"""Regenerates js/search-data.js from the project cards in index.html.

index.html's project-grid is the single source of truth for project
metadata (title, role, tags). Run this after adding/editing a project
card so the header search stays in sync:

    python scripts/build_search_index.py
"""

import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

CARD_RE = re.compile(
    r'<a class="project-card" href="projects/(?P<slug>[\w-]+)\.html"[^>]*>.*?'
    r'<h3>(?P<title>.*?)</h3>.*?'
    r'<p class="project-role">(?P<role>.*?)</p>.*?'
    r'<ul class="tech-tags">(?P<tags>.*?)</ul>',
    re.DOTALL,
)
TAG_RE = re.compile(r'<li(?:\s+class="tag-spacer"[^>]*)?>(.*?)</li>')
TAG_STRIP_RE = re.compile(r"<[^>]+>")
BR_RE = re.compile(r"<br\s*/?>", re.IGNORECASE)


def strip_tags(text):
    text = BR_RE.sub(" ", text)
    return html.unescape(TAG_STRIP_RE.sub("", text).strip())


def main():
    index_html = (ROOT / "index.html").read_text(encoding="utf-8")
    entries = []
    for match in CARD_RE.finditer(index_html):
        tags = [
            strip_tags(t) for t in TAG_RE.findall(match.group("tags")) if strip_tags(t)
        ]
        entries.append(
            {
                "title": strip_tags(match.group("title")),
                "role": strip_tags(match.group("role")),
                "url": f"projects/{match.group('slug')}.html",
                "tags": tags,
            }
        )

    if not entries:
        raise ValueError("no project cards matched, check CARD_RE against index.html")

    js = (
        "// Auto-generated by scripts/build_search_index.py. Do not edit by hand,\n"
        "// edit index.html's project cards and rerun the script instead.\n"
        "const SEARCH_INDEX = "
        + json.dumps(entries, indent=2)
        + ";\n"
    )

    out_path = ROOT / "js" / "search-data.js"
    out_path.write_text(js, encoding="utf-8")
    print(f"wrote {out_path.relative_to(ROOT)} ({len(entries)} projects)")


if __name__ == "__main__":
    main()
